### ISSUE TITLE
Broken Links & small misstake

### ISSUE THREAD

**Issue by Nudin** [nigamanthsrivatsan/nigamanth.com#2]
Just wanted to let you know:
- Currently, the links on https://www.nigamanth.com/ are broken.
- The second exercise [here](https://www.nigamanth.com/blog/2023/cube-roots-trick.html) is wrong. 653,503 is no perfect cube – 65**8**503 is
- There's no easy way to contact you on the site
- Oh, and did you know it's even easier to calculate the fifth-root mentally? ;)

**Comment by nigamanthsrivatsan** [comment]
Yeah I know about the mistake. 
I'll add it soon, it's really a work in progress, and no I do not know about the fifth-root.
